services:
  - docker

before_install:
  - docker run -d -p 80:8300 --name unit vladkras/nginx-unit-php7

install:
  - docker exec unit curl -X PUT -d @/config.json --unix-socket /run/control.unit.sock

script:
  - curl -I http://localhost
